METER = 'SAM000012597'
GATEWAY = 'HHRND00021'
SERVICE_POINT = METER


testcase_list = [
    # {'tp_number': 'TPxxxxx-0001-C1',
    #  'service_name': 'set_schedule',
    #  'test_data_path': r".\Database\SetSchedule.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0002-C1',
    #  'service_name': 'get_Supply_Control',
    #  'test_data_path': r".\Database\GetSupplyControlCode.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 3,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0003-C1',
    #  'service_name': 'change_price',
    #  'test_data_path': r".\Database\ChangePrice.xls",
    #  'iteration_from': 3,
    #  'iteration_to': 3,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0004-C1',
    #  'service_name': 'change_prepayment_configuration',
    #  'test_data_path': r".\Database\ChangePrepaymentConfiguration.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0005-C1',
    #  'service_name': 'change_billing_dates',
    #  'test_data_path': r".\Database\ChangeBillingDates.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },
    #
    {'tp_number': 'TPxxxxx-0006-C1',
     'service_name': 'change_tariff_plan',
     'test_data_path': r".\Database\ChangeTariffPlan.xls",
     'iteration_from': 4,
     'iteration_to': 4,
     'spn': SERVICE_POINT,
     'meter': METER,
     'gateway': GATEWAY,
     },
    #
    # {'tp_number': 'TPxxxxx-0007-C1',
    #  'service_name': 'change_event_configuration',
    #  'test_data_path': r".\Database\ChangeEventConfiguration.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0009-C1',
    #  'service_name': 'change_profile_configuration',
    #  'test_data_path': r".\Database\ChangeProfileConfiguration.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0010-C1',
    #  'service_name': 'send_text_message',
    #  'test_data_path': r".\Database\SendTextMessage.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0011-C1',
    #  'service_name': 'initialise_meter',
    #  'test_data_path': r".\Database\InitialiseMeter.xls",
    #  'iteration_from': 3,
    #  'iteration_to': 3,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0012-C1',
    #  'service_name': 'change_gas_parameters',
    #  'test_data_path': r".\Database\ChangeGasParameters.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0013-C1',
    #  'service_name': 'change_co2_configuration',
    #  'test_data_path': r".\Database\ChangeCO2Configuration.xls",
    #  'iteration_from': 2,
    #  'iteration_to': 2,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },

    # {'tp_number': 'TPxxxxx-0014-C1',
    #  'service_name': 'change_system_parameters',
    #  'test_data_path': r".\Database\ChangeSystemParameters.xls",
    #  'iteration_from': 18,
    #  'iteration_to': 18,
    #  'spn': SERVICE_POINT,
    #  'meter': METER,
    #  'gateway': GATEWAY,
    #  },


]
